swagger: "2.0"
info:
  version: "0.0.1"
  title: Blackjack
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths
basePath: /api/v1
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /player:
    # binds a127 app logic to a route
    x-swagger-router-controller: player
    get:
      description: Get player by id
      # used as the method name of the controller
      operationId: getPlayer
      parameters:
        - name: id
          in: query
          description: The id of the player
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GetPlayerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GetPlayerResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
